### ISSUE TITLE
sum.js 注意排版

### ISSUE THREAD

**Issue by azole** [yichenkung/node-workshop#1]
![image](https://user-images.githubusercontent.com/2560515/127745138-87954b6f-549b-43d0-a178-21d10a027783.png)

程式碼是正確的，但這樣的排版可能會比較難閱讀跟理解，特別是並沒有用 {} 來作出區塊了，`result += i` 再沒有縮進的話，會比較難閱讀，所以會建議可以加上 {} 跟縮進(indent)，讓整個程式碼更容易閱讀的話，未來也比較不會有 bug。

**Comment by yichenkung** [comment]
了解，謝謝老師。
